In [1]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import numpy as np
import xarray as xr
from glob import glob
import os
from netCDF4 import Dataset
import pandas as pd
from datetime import datetime, date, timedelta
from pathlib import Path
import scipy
import scipy.ndimage
from mpl_toolkits.axes_grid1 import ImageGrid
import math
import cc3d
from scipy import stats

from mpl_toolkits.axes_grid1 import make_axes_locatable
from matplotlib.colors import ListedColormap

In [26]:
t=84
#source_input_dir = Path("/mnt/stor-pool-01/projects/heus/BNF/Ensemble_Tests/512_512_50m_12km_chbuff/2025-07-01_normal_shell/thijs")
source_input_dir = Path("/mnt/stor-pool-01/projects/heus/rico/doubledump")
ds_e = xr.open_dataset(source_input_dir / "netE.nc", decode_times=False)
ds_shell_prop = xr.open_dataset(source_input_dir / "shell.nc", decode_times=False)

e_slice = ds_e.isel(time=t)
shell_prop_slice = ds_shell_prop.isel(time=t)

In [22]:
np.unique(ds_e.isel(time=0).netE_flux_x_shell.values)

array([9.96921e+36], dtype=float32)

In [14]:
ds_e.time.values[60]

np.float32(9.96921e+36)

In [19]:
from decimal import Decimal
print(Decimal(float(ds_e.time.values[60])))

9969209968386869046778552952102584320


In [20]:
from decimal import Decimal
print(Decimal(float(ds_e.time.values[61])))

9969209968386869046778552952102584320


In [27]:
ds_e.time.values

array([1.80000e+03, 3.60000e+03, 5.40000e+03, 7.20000e+03, 9.00000e+03,
       1.08000e+04, 1.26000e+04, 1.44000e+04, 1.62000e+04, 1.80000e+04,
       1.98000e+04, 2.16000e+04, 2.34000e+04, 2.52000e+04, 2.70000e+04,
       2.88000e+04, 3.06000e+04, 3.24000e+04, 3.42000e+04, 3.60000e+04,
       3.78000e+04, 3.96000e+04, 4.14000e+04, 4.32000e+04, 4.50000e+04,
       4.68000e+04, 4.86000e+04, 5.04000e+04, 5.22000e+04, 5.40000e+04,
       5.58000e+04, 5.76000e+04, 5.94000e+04, 6.12000e+04, 6.30000e+04,
       6.48000e+04, 6.66000e+04, 6.84000e+04, 7.02000e+04, 7.20000e+04,
       7.38000e+04, 7.56000e+04, 7.74000e+04, 7.92000e+04, 8.10000e+04,
       8.28000e+04, 8.46000e+04, 8.64000e+04, 9.96921e+36, 9.96921e+36,
       9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
       9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
       9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36,
       9.96921e+36, 9.96921e+36, 9.96921e+36, 9.96921e+36, 9.969

In [28]:
ds_shell_prop.time.values

array([    0.,  1799.,  1800.,  3597.,  3600.,  5398.,  5400.,  7197.,
        7200.,  8998.,  9000., 10798., 10800., 12598., 12600., 14398.,
       14400., 16197., 16200., 17998., 18000., 19798., 19800., 21599.,
       21600., 23398., 23400., 25199., 25200., 26999., 27000., 28799.,
       28800., 30598., 30600., 32399., 32400., 34198., 34200., 35998.,
       36000., 37798., 37800., 39599., 39600., 41399., 41400., 43198.,
       43200., 44998., 45000., 46798., 46800., 48598., 48600., 50397.,
       50400., 52199., 52200., 53998., 54000., 55799., 55800., 57598.,
       57600., 59398., 59400., 61198., 61200., 62998., 63000., 64799.,
       64800., 66599., 66600., 68398., 68400., 70199., 70200., 71998.,
       72000., 73799., 73800., 75599., 75600., 77398., 77400., 79198.,
       79200., 80999., 81000., 82799., 82800., 84598., 84600., 86399.,
       86400.], dtype=float32)

In [ ]:
np.unique(e_slice.netE_flux_x_shell.values)

In [12]:
ds_e

<xarray.Dataset> Size: 431GB
Dimensions:            (time: 323, x: 512, y: 512, z: 159, xh: 512, yh: 512,
                        zh: 159)
Coordinates:
  * time               (time) float32 1kB 3.6e+03 7.2e+03 ... 9.969e+36
  * x                  (x) float32 2kB 25.0 75.0 125.0 ... 2.552e+04 2.558e+04
  * y                  (y) float32 2kB 25.0 75.0 125.0 ... 2.552e+04 2.558e+04
  * z                  (z) float32 636B 10.0 30.0 52.0 ... 1.146e+04 1.214e+04
  * xh                 (xh) float32 2kB 0.0 50.0 100.0 ... 2.55e+04 2.555e+04
  * yh                 (yh) float32 2kB 0.0 50.0 100.0 ... 2.55e+04 2.555e+04
  * zh                 (zh) float32 636B 0.0 20.0 41.0 ... 1.114e+04 1.18e+04
Data variables:
    netE_ql            (time, z, y, x) float32 54GB ...
    netE_flux_x_ql     (time, z, y, xh) float32 54GB ...
    netE_flux_y_ql     (time, z, yh, x) float32 54GB ...
    netE_flux_z_ql     (time, zh, y, x) float32 54GB ...
    netE_shell         (time, z, y, x) float32 54GB 9.969e+36 9.969e+36 ... nan
    netE_flux_x_shell  (time, z, y, xh) float32 54GB ...
    netE_flux_y_shell  (time, z, yh, x) float32 54GB ...
    netE_flux_z_shell  (time, zh, y, x) float32 54GB ...

In [4]:
shell_prop_slice

<xarray.Dataset> Size: 167MB
Dimensions:  (z: 159, y: 512, x: 512)
Coordinates:
    time     float32 4B 1.511e+05
  * z        (z) float32 636B 10.0 30.0 52.0 ... 1.083e+04 1.146e+04 1.214e+04
  * y        (y) float32 2kB 25.0 75.0 125.0 ... 2.548e+04 2.552e+04 2.558e+04
  * x        (x) float32 2kB 25.0 75.0 125.0 ... 2.548e+04 2.552e+04 2.558e+04
Data variables:
    shell    (z, y, x) float32 167MB ...